### ISSUE TITLE
[BUG] log is spammed because of missing dbus socket

### ISSUE THREAD

**Issue by shawly** [linuxserver/docker-calibre#162] opened 2024-10-05 14:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My log is spammed by this error:

```
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 713, in open
  File "calibre/devices/usbms/device.py", line 587, in open_linux
calibre.devices.errors.DeviceError: Unable to mount main memory (Error code: 1)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 562, in do_mount
  File "calibre/devices/udisks.py", line 139, in mount
  File "calibre/devices/udisks.py", line 44, in __enter__
  File "jeepney/io/blocking.py", line 342, in open_dbus_connection
  File "jeepney/io/blocking.py", line 310, in prep_socket
  File "jeepney/io/blocking.py", line 307, in with_sock_deadline
FileNotFoundError: [Errno 2] No such file or directory
```

It seems that calibre is expecting a dbus socket on `/run/dbus/system_bus_socket` but kasmvnc doesn't provide that.
I tried linking the dbus session under /tmp/dbus-* to `/run/dbus/system_bus_socket` and afterwards the following error message is spammed in the logs:

```
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 713, in open
  File "calibre/devices/usbms/device.py", line 587, in open_linux
calibre.devices.errors.DeviceError: Unable to mount main memory (Error code: 1)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 562, in do_mount
  File "calibre/devices/udisks.py", line 140, in mount
  File "calibre/devices/udisks.py", line 102, in mount
  File "calibre/devices/udisks.py", line 96, in filesystem_operation_message
  File "calibre/devices/udisks.py", line 89, in device
  File "calibre/devices/udisks.py", line 75, in iter_block_devices
  File "calibre/devices/udisks.py", line 65, in introspect
  File "calibre/devices/udisks.py", line 60, in send
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.ServiceUnknown] ('The name org.freedesktop.UDisks2 was not provided by any .service files',)
```

Apart from this error calibre seems to work, but with the log being spammed like this is not helping when actually trying to debug issues.
I have disabled the logging driver for now to get around this.

Strangely enough this only happens on my home server, if I run the container on my desktop (EndeavourOS) it does not occur.

Could this be related to any apparmor or other security settings?

I already tried starting the container with privileged mode but that didn't help.

### Expected Behavior

No logspam.

### Steps To Reproduce

Setup the container according to the documentation by lsio.

### Environment

```markdown
- OS: Ubuntu Server 24.04
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  app:
    restart: always
    environment:
      TZ: Europe/Berlin
      PUID: '1000'
      PGID: '1000'
    labels:
      com.centurylinklabs.watchtower.enable: true
      traefik.enable: true
      traefik.http.services.calibre.loadbalancer.server.port: 8080
      traefik.http.services.calibre-content.loadbalancer.server.port: 8081
    volumes:
    - /srv/calibre/config:/config
    - /mnt/user/ebooks:/mnt/user/ebooks
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
    - seccomp:unconfined
    networks:
      default:
      traefik_net:

networks:
  default:
  traefik_net:
    external: true
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v7.19.0-ls305
Build-date: 2024-10-02T06:45:53+00:00
───────────────────────────────────────
    
...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+...+......+.....+......+...+.......+......+..+...+...+.+...+...+........+............+...+............+....+...........+....+...+.....+......+....+..+.+........+.+.....+...+.+..+...+......................+...+...........+...+.+......+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.+.+.........+...+..+...+..........+..+.+...........+.+.....+...+.+.....+...+...+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..........+.......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...........+....+...+......+......+.....+......+...+....+...........+......+.........+.......+............+..+...+.+.........+......+..+...+....+...+..+............+.+........+.+........+...+...............+...+..........+...............+..+.......+...+.........+.....+...+.+.....+.......+............+........+...+.+...........+.............+..+.......+.....+......+...................+..+.........+......+................+.....+...+......+.............+..+.+..+.+...........+...+...+....+......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.2.0 - built Sep 28 2024 19:15:41
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

[ls.io-init] done.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
Obt-Message: Xinerama extension is not present on the server
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
19
 2024-10-05 14:23:27,735 [INFO] websocket 0: got client connection from 127.0.0.1
 2024-10-05 14:23:27,743 [PRIO] Connections: accepted: @172.17.0.1_1728138207.735784::websocket
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 713, in open
  File "calibre/devices/usbms/device.py", line 587, in open_linux
calibre.devices.errors.DeviceError: Unable to mount main memory (Error code: 1)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 562, in do_mount
  File "calibre/devices/udisks.py", line 139, in mount
  File "calibre/devices/udisks.py", line 44, in __enter__
  File "jeepney/io/blocking.py", line 342, in open_dbus_connection
  File "jeepney/io/blocking.py", line 310, in prep_socket
  File "jeepney/io/blocking.py", line 307, in with_sock_deadline
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 713, in open
  File "calibre/devices/usbms/device.py", line 587, in open_linux
calibre.devices.errors.DeviceError: Unable to mount main memory (Error code: 1)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "calibre/devices/usbms/device.py", line 562, in do_mount
  File "calibre/devices/udisks.py", line 139, in mount
  File "calibre/devices/udisks.py", line 44, in __enter__
  File "jeepney/io/blocking.py", line 342, in open_dbus_connection
  File "jeepney/io/blocking.py", line 310, in prep_socket
  File "jeepney/io/blocking.py", line 307, in with_sock_deadline
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by drizuid** [comment] 2024-12-23 15:55
We are unable to reproduce this in any of our testing across the team. Closing this as can't reproduce. Note, OP also indicates this only occurs on one of their systems and not another which is a clear indication that this is a host issue, not a container issue.

**Closed by drizuid** 2024-12-23 15:55 UTC
Labels: no-issue-activity
