### ISSUE TITLE
Since latest update, calibre runs, but connection not working

### ISSUE THREAD

**Issue by maxximux2000** [linuxserver/docker-calibre#104] opened 2022-09-28 19:53 UTC
I have multiples docker containers on the same server that are all working exept Calibre since the latest update. I get a connection refused by server, I check the docker container status in Portainer.IO and it's working as expected, but I cannot connect from the server itself using localhost or from another computer on the same network using the server ip:8080. I tried multiples browser as well (Chrome and Firefox) with same result. Server is Ubuntu 22.04.1 LTS

**Comment by aptalca** [comment] 2022-09-30 17:08
You probably have locally cached image of a 6.5.0 version that was pushed before the rebase to jammy. Do a docker pull and recreate, it will likely no longer work.

Make sure you add the seccomp arg that's now in the readme

**Comment by dangmai** [comment] 2022-09-30 17:15
Good point about it being locally cached! I will have to figure out a way to add the seccomp profile to a Kubernetes pod then, since it's not even running Docker (it's running containerd). Hopefully there is a way around it.

**Comment by aptalca** [comment] 2022-09-30 17:17
Pretty sure k8s supports security options. Let us know if it works because there are too many users reporting similar issues with little to no confirmation of whether that solved their issue

**Comment by dangmai** [comment] 2022-09-30 19:11
Yeah same here, `Unconfined` seccomp policy does not help.

**Comment by maxximux2000** [comment] 2022-10-03 19:19
I have personally downgraded to version 6.4.0 and now I can access the calibre library without problem, I will continue to monitor the new release to see if this has been resolved.

**Comment by j0nnymoe** [comment] 2022-10-03 19:36
Multiple reasons why you could be having issues here. Unless people provide information about their deployment and hardware/os they're using, we can't help. (Hence why this issue is marked as invalid)

**Comment by aptalca** [comment] 2022-10-04 15:21
What's your compose yaml?

**Comment by PriamX** [comment] 2022-10-04 17:22
@aptalca FYI...

```
 calibre:
    image: linuxserver/calibre
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Denver
      - SUBFOLDER=/calibre/
    volumes:
      - /media/docker/appdata/calibre:/config
      - /media/books/calibre/library:/books
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - mynet
    healthcheck:
      test: (curl --fail -s http://localhost:8080/ && curl --fail -s http://localhost:8081/) || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
```

**Comment by aptalca** [comment] 2022-10-04 17:30
Can you exec into the container `docker exec -it calibre bash`
and then run this?
`s6-envdir -fn -- /var/run/s6/container_environment /bin/bash -c 'umask ${UMASK:-022} && /usr/bin/calibre'`

**Comment by PriamX** [comment] 2022-10-04 17:48
@aptalca yes, no prob:

```
[root@mediaserv ~]# docker exec -it calibre /bin/bash
root@0369d649e423:/# s6-envdir -fn -- /var/run/s6/container_environment /bin/bash -c 'umask ${UMASK:-022} && /usr/bin/calibre'
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

Aborted (core dumped)
root@0369d649e423:/#
```

**Comment by aptalca** [comment] 2022-10-04 17:52
That's the same error I get when I don't set the seccomp bit correctly

**Comment by aptalca** [comment] 2022-10-04 18:01
OK, so what do you experience when you try to open the gui? An error about child process? or nothing?

If nothing, exec into the container and run `echo "xterm" > /defaults/autostart` and restart the container
You should hopefully see terminal window in the gui. Run `calibre` and see what happens

**Comment by PriamX** [comment] 2022-10-04 18:10
When I open the GUI (port 8080), the only thing displayed on the web page is `Cannot GET /`

Making that change (putting xterm in the autostart) and restarting the calibre container, I still get the same error in the webpage, `Cannot GET /`

The tail of the logfile looks pretty-much the same:

```
4.sync,8.70320119;
4.sync,8.70320369;
4.sync,8.70320619;
4.sync,8.70320870;
4.sync,8.70321120;
[2022-10-04 12:05:45] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[2022-10-04 12:05:45] [Connection 1]  Closing guacd connection
[2022-10-04 12:05:45] [Connection 1]  Client connection closed
guacd[244]: ERROR:	User is not responding.
guacd[244]: INFO:	User "@bf8a4622-61c4-4d7d-9e4f-375da5699de4" disconnected (0 users remain)
guacd[244]: INFO:	Last user of connection "$ccc33915-a25e-48fd-bcaa-711af54872d5" disconnected
guacd[244]: INFO:	Internal RDP client disconnected
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x5617f289d860
guacd[191]: INFO:	Connection "$ccc33915-a25e-48fd-bcaa-711af54872d5" removed.
```

**Comment by aptalca** [comment] 2022-10-04 18:15
Are you reverse proxying or accessing directly? What address are you using?

**Comment by PriamX** [comment] 2022-10-04 18:20
I did have a reverse proxy set up on it (swag), however, I'm not using that to access it while trying to figure this out. I have port 8080 and 8081 published to the host and am using http://hostip:8080 from a Windows PC (using Chrome) on the same LAN. The host is Linux and I've also tried using Firefox on the host using http://localhost:8080 with the same result.

**Comment by PriamX** [comment] 2022-10-04 18:36
Wait, my bad. `http://localhost/calibre:8080` does get me into the xterm, trying your test...

That does work when I execute `calibre` from the xterm.

**Comment by PriamX** [comment] 2022-10-04 18:41
Reconfirming, going back to `s6-envdir -fn -- /var/run/s6/container_environment /bin/bash -c 'umask ${UMASK:-022} && /usr/bin/calibre $CLI_ARGS'` in the `/defaults/autostart` file does NOT work. Testing with `http://localhost/calibre:8080` (as I should have done originally), there's just a black dot on the left-hand side of the window.

Let my try going back to 6.4.0 like the OP did, because I tested that one using the wrong URL too.

**Comment by aptalca** [comment] 2022-10-04 18:46
🤦
you set the subfolder var to `/calibre/` so it's accessible at that baseurl

I'm going to go ahead and close this issue because it really went off track

Anyone who's having issues with the gui not being accessible try the following:
- add the seccomp bit that is now in the readme
- pay attention to the subfolder var setting
- access directly, without a reverse proxy
- try creating a container with the most basic arguments and without a volume map, like `docker run -d --rm --name test -p 8080:8080 --security-opt seccomp=unconfined lscr.io/linuxserver/calibre` and see if that brings up a gui

If none of those work, then open a new issue and completely fill out the issue template

**Closed by aptalca** 2022-10-04 18:46 UTC
Labels: invalid

**Comment by PriamX** [comment] 2022-10-04 18:49
Confirmed, like the OP, 6.4.0 tag does work, the "lastest" tag does NOT. Since this is being closed, like the OP, I'll skip this version and try again in a later version.

Thank you for your help.

**Comment by maxximux2000** [comment] 2022-10-04 19:47
I was able to make it work using the docker run command at : https://github.com/linuxserver/docker-calibre/blob/master/README.md
modified the variables and it's working using version 6.6.1. 

I'm happy :) 

Thanks

**Comment by dangmai** [comment] 2022-10-04 22:54
For folks on Kubernetes, I'm pretty sure this has to do with the container runtime. When I switch from containerd to docker as the underlying runtime, the image works again. I'm still trying to find the root cause for it, but I'm suspecting that it has to do with how containerd handles seccomp policies.

**Comment by brettinternet** [comment] 2022-10-07 00:37
Likewise I'm seeing issues with 6.6.1 on both arm64 and amd64 in my K3s cluster where I see logs the same as this https://github.com/linuxserver/docker-calibre/issues/104#issuecomment-1263800049 and nothing after `custom-init] No custom services found, skipping...`. I access my services behind a reverse proxy. However, I'm not sure that's relevant since the logs are not showing guacd even starting up.

I have added this option to the deployment container, however it had no effect. https://kubernetes.io/docs/tutorials/security/seccomp/

```
securityContext:
  seccompProfile:
    type: Unconfined
```

Like the others, I was able to get the container to work as expected when pointing to `6.4.0`.

**Comment by dangmai** [comment] 2022-10-08 22:39
So the root cause for this for folks running k3s is because of IPv6. `s6` periodically polls `127.0.0.1` on port `3350` (see [here](https://github.com/linuxserver/docker-baseimage-rdesktop/blob/jammy/root/etc/s6-overlay/s6-rc.d/svc-xrdp-sesman/run#L7)) to check whether `xrdp-sesman` is up or not. However sesman only listens to the ipv6 interface, so that check fails and none of the services that depends on sesman gets to run (e.g. `svc-xrdp`, `svc-web`).

There is already a pending PR: https://github.com/linuxserver/docker-baseimage-rdesktop/pull/20/files to fix this issue, so when that is merged and this repo pulls in a new base image with that fix, `calibre` will start working again.

**Comment by Iristyle** [comment] 2022-11-06 07:07
Also having issues on my Synology which is currently stock at Docker engine `20.10.03`. When I add `seccomp:unconfined` to my `docker-compose.yml` that at least allows the `latest` image to start, but there are a lot of errors in the container logs and the RDP session won't render in the browser.

If I pin back to `6.4.0` as mentioned in the thread, I don't have any issues. I haven't yet tried 6.5, 6.6, 6.7, etc.

**Comment by aptalca** [comment] 2022-11-15 15:24
@dangmai apparently our sesman fix seems to have cause other issues. All rdesktop-web based images with that fix is taking 15-20 seconds to display the gui on browser connection. We're gonna try setting the sesman listen address to `0.0.0.0`, which seems to fix the connection/load issues, but can you check that on k3s?
I believe you just need to spin up a container, don't open the gui yet, exec into the container and edit `/etc/xrdp/sesman.ini` and change `;ListenAddress=127.0.0.1` to `ListenAddress=0.0.0.0` (uncomment and set to `0.0.0.0`).
Then you can restart the container and see if it works

Thanks

**Comment by BoKKeR** [comment] 2023-03-23 06:17
Neither does 6.4.0 or newer work for me 

```
[2023-03-23 07:15:17] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[2023-03-23 07:15:17] [Connection 1]  Closing guacd connection
[2023-03-23 07:15:17] [Connection 1]  Client connection closed
guacd[258]: ERROR:      User is not responding.
guacd[258]: INFO:       User "@cacddc80-33b9-4b8d-a863-d0cca30c27fe" disconnected (0 users remain)
guacd[258]: INFO:       Last user of connection "$5fda43b4-b331-4e21-b213-f90e05a72a24" disconnected
guacd[258]: INFO:       Internal RDP client disconnected
guacd[220]: INFO:       Connection "$5fda43b4-b331-4e21-b213-f90e05a72a24" removed.
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x55e450ecb9c0
```
